# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant Settings
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.201"
  
  #VirtualBox Settings
  config.vm.provider "virtualbox" do |vb|
	vb.gui = false
	vb.name = "AnsibleSlave01"
    vb.memory = "1024"
	vb.cpus = "1"
  end
end